import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header/Header";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const iranSansXFont = localFont({
  src: [
    { path: "../fonts/IRANSansXFaNum-Thin.woff", weight: "100" },
    { path: "../fonts/IRANSansXFaNum-Light.woff", weight: "300" },
    { path: "../fonts/IRANSansXFaNum-Regular.woff", weight: "400" },
    { path: "../fonts/IRANSansXFaNum-Medium.woff", weight: "500" },
    { path: "../fonts/IRANSansXFaNum-DemiBold.woff", weight: "600" },
    { path: "../fonts/IRANSansXFaNum-Bold.woff", weight: "700" },
    { path: "../fonts/IRANSansXFaNum-ExtraBold.woff", weight: "800" },
    { path: "../fonts/IRANSansXFaNum-Black.woff", weight: "900" },
  ],
  variable: "--font-iranSans",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${iranSansXFont.variable} font-iranSans flex flex-col min-h-screen`}>
        <Header />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
