import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header/Header";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const peydaFont = localFont({
  src: [
    { path: "../fonts/PeydaWeb-Black.woff", weight: "100" },
    { path: "../fonts/PeydaWeb-ExtraBold.woff" },
    { path: "../fonts/PeydaWeb-Thin.woff" },
    { path: "../fonts/peydaWeb-light.woff", weight: "300" },
    { path: "../fonts/PeydaWeb-Regular.woff", weight: "400" },
    { path: "../fonts/PeydaWeb-Medium.woff", weight: "500" },
    { path: "../fonts/PeydaWeb-Black.woff", weight: "900" },
  ],
  variable: "--font-peyda",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${peydaFont.variable} font-peyda flex flex-col min-h-screen`}>
        <Header />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
